# Credits on https://github.com/rybbit-io/rybbit

services:
  caddy:
    image: caddy:2.10.0
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # Needed for HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Mount Caddy config file
      - caddy_data:/data # Mount persistent data volume for certs etc.
      - caddy_config:/config # Mount persistent config volume
      - /etc/ssl/certs:/etc/ssl/certs:ro # Mount system certificates (read-only)
      - /etc/ssl/private:/etc/ssl/private:ro # Mount system private keys (read-only)
    environment:
      # Pass domain name for use in Caddyfile
      - DOMAIN_NAME=${DOMAIN_NAME}
      # Email is configured via Caddyfile global options
      - EMAIL=${EMAIL}
      # Cloudflare API token for DNS management (optional)
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN:-}
networks:
  caddy_network:
    external: true
  default:
    driver: bridge

volumes:
  caddy_data: # Persistent volume for Caddy's certificates and state
  caddy_config: # Persistent volume for Caddy's configuration cache (optional but good practice)
